wip: add rusticl to the site
MightyCreak/mesamatrix pull request #270
Opened 2023-05-18 17:50 UTC by norablackcat

This is a work in progress and I'm not really a php developer at all. Currently fails to parse. 

Parsing based on this merge req https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/23055

closes: https://github.com/MightyCreak/mesamatrix/issues/269

2023-05-23 19:54 UTC, norablackcat commented
Everything should be ready now baring any changes from reviewers on mesa

2023-06-05 21:33 UTC, MightyCreak requested changes
Just a tiny change, but LGTM, thanks!

2023-06-05 21:33 UTC, MightyCreak commented on src/Leaderboard/Leaderboard.php
> +
Just an extra newline that can be removed

2023-06-08 14:07 UTC, norablackcat commented
Upstream has been merged :crab:

2023-06-08 14:28 UTC, illwieckz commented
I tested this, that looks good! 🙂️

Why not listing RustiCL before Clover? I know RustiCl is still experimental, but Clover is not less experimental, just experimental since more time, and is less complete.

2023-06-09 06:02 UTC, zboszor commented
> Why not listing RustiCL before Clover? I know RustiCl is still experimental, but Clover is not less experimental, just experimental since more time, and is less complete.

I think it's not really interesting. But it fits alphabetical order: Clover < Rusticl.

2023-06-09 08:42 UTC, norablackcat commented
need to update this to add r600 as it's been merged so do not merge yet. 



> > Why not listing RustiCL before Clover? I know RustiCl is still experimental, but Clover is not less experimental, just experimental since more time, and is less complete.
> 
> I think it's not really interesting. But it fits alphabetical order: Clover < Rusticl.

Yeah that's the order I did it in initially although it's probably better to put rusticl above because it supports more and is actually maintained

2023-06-11 06:24 UTC, norablackcat commented
Changed to display rusticl first and added the possible drivers rusticl will support in the future.

Need to double check with Karol to make sure those drivers are correct

2023-06-12 11:49 UTC, norablackcat commented
It was decided that we are not going to list unsupported drivers and just update the list later when the need arises for some wip driver support

this should be ready for merge

2023-06-12 16:10 UTC, MightyCreak commented
Hmmm there are some issues with the tests as well, I'm taking a look at it right now.

2023-06-12 16:30 UTC, MightyCreak approved these changes
Pushed some lint and tests fixes, but it's all good now!

2023-06-12 16:32 UTC, merged